# Generated by Django 6.0.2 on 2026-02-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
